/*
 * A Maxima script that reproduces expected results of the test module
 * 'test/polyTest.cpp'.
 *
 * From a shell, run the script as:
 *   maxima -b /path/to/poly.mac
 *
 * From Maxima/wxMaxima, the script can be run as:
 *   batch("/path/to/poly.mac")
 */


block(
  [i, desc, p1, p2],
  local(pol1, t, trev, tr, z, p, q, qint),

  pol1(x) := -4.1,
  print("pol1(x) = ", pol1(x) ),
  t(x) := 2.1 + 1.0*x - 0.72*x^2 + 1.0*x^3 + 0.0*x^4,
  print("t(x) = ", t(x) ),

  for i: 0 thru 3 do
    print("c", i, "(t(x)) = ", coeff(t(x), x, i) ), 

  t(x) := 2.1 - 0.72*x + 1*x^2,
  print("t(x) = ", t(x) ),
  t(x) := 2.1 - 0.72*x + 0.2*x^2 + 1*x^3,
  print("t(x) = ", t(x) ),
  t(x) := 2.1 - 0.72*x + 0.2*x^2 + 1*x^3 + 5*x^7,
  print("t(x) = ", t(x) ),

  desc : makelist( coeff( t(x), x, hipow(t(x),x )-i ), i, 0, hipow(t(x),x ) ),
  print("Coefficients of t(x) in descending order: ", desc ),
  trev(x) := sum(desc[i] * x^(i-1), i, 1, length(desc)),
  print("trev(x) = ", trev(x) ),
  tr(x) := sum( (if abs(coeff(t(x),x,i))<0.75 then 0 else coeff(t(x),x,i)) * x^i, i, 0, hipow(t(x), x)),
  print("tr(x) = ", tr(x) ),
  t(x) := 78.12,
  print("t(x) = ", t(x) ),
  z(x) := 0,
  print("z(x) = ", z(x) ),

  p(x) := 2 + 3*x - 4*x^2 - 7*x^3 + 2*x^4 + 1*x^5,
  print("p(x) = ", p(x) ),
  q(x) := -1 + 5*x - 3*x^2 + 1*x^3,
  print("q(x) = ", q(x) ),
  print("p(-1.2) = ", p(-1.2) ),
  print("q(0.7) = ", q(0.7) ),
  print("p(x) + q(x) = ", p(x) + q(x) ),
  print("q(x) + p(x) = ", q(x) + p(x) ),
  print("p(x) - q(x) = ", p(x) - q(x) ),
  print("q(x) - p(x) = ", q(x) - p(x) ),
  print("p(x) * q(x) = ", expand(p(x) * q(x)) ),
  print("q(x) * p(x) = ", expand(q(x) * p(x)) ),

  print("0.3 * p(x) = ", expand(0.3 * p(x)) ),
  print("0.5 * q(x) = ", expand(0.5 * q(x)) ),
  print("p(x) + 2 = ", p(x) + 2 ),
  print("2 + p(x) = ", 2 + p(x) ),
  print("q(x) - 3 = ", q(x) - 3 ),
  print("4 - q(x) = ", 4 - q(x) ),
  p1 : p(x) + 10,
  print("p1(x) = ", p1 ),
  p2 : p1 - 10,
  print("p2(x) = ", p2 ),

  print("p'(x) = ", diff(p(x), x) ),
  qint(x) := ev(integrate(q(x), x)),
  print("Integral of q(x) = ", qint(x) ),
  print("qint'(x) = ", diff(qint(x), x) ),

  print("q(x) / 5 = ", expand(divide(q(x), 5)) ),
  print("2 / q(x) = ", divide(2, q(x)) ),

  print("q(x) / 2 = ", divide(q(x), 2) ),

  p(x) := -1 + 0*x + 1*x^2 + 2*x^3 - 1*x^4 + 4*x^5,
  print("p(x) = ", p(x) ),
  q(x) := 1 + 0*x + 1*x^2,
  print("q(x) = ", q(x) ),
  print("p(x) / q(x) = ", divide(p(x), q(x)) ),

  p(x) := -4 + 0*x -2*x^2 + 1*x^3,
  print("p(x) = ", p(x) ),
  q(x) := -3 + 1*x,
  print("q(x) = ", q(x) ),
  print("p(x) / q(x) = ", divide(p(x), q(x)) ),

  p(x) := -5 + 3*x + 0*x^2 - 6*x^3 + 4*x^4,
  print("p(x) = ", p(x) ),
  q(x) := -1 + 2*x,
  print("q(x) = ", q(x) ),
  print("p(x) / q(x) = ", divide(p(x), q(x)) )

)$
