/*
 * A Maxima script that reproduces expected results of the test module
 * 'test/rootfindTest.cpp'.
 *
 * From a shell, run the script as:
 *   maxima -b /path/to/rootfind.mac
 *
 * From Maxima/wxMaxima, the script can be run as:
 *   batch("/path/to/rootfind.mac")
 */


block(
  local(f, d, d2),

  f(x) := sin(x)/x - 1/2,
  print("f(x) = ", f(x) ),
  print("lim(f(x), x->0) = ", limit(sin(x)/x, x, 0) ),

  d(x) := ev(diff(f(x), x) ),
  print("f'(x) = ", d(x)),
  print("lim(f'(x), x->0) = ", limit(d(x), x, 0) ),

  d2(x) := ev(diff(f(x), x, 2)),
  print("f''(x) = ", d2(x) ),
  print("lim(f''(x), x->0) = ", limit(d2(x), x, 0) ),

  print("Root of f(x) between 1 and 3: ", find_root(f(x), x, 1, 3) )
)$
