/*
 * A Maxima script that reproduces the first part of expected results of the
 * test module 'test/specfunTest.cpp'.
 * The other part is performed in 'scripts/test/specfun.py'.
 *
 * From a shell, run the script as:
 *   maxima -b /path/to/specfun.mac
 *
 * From Maxima/wxMaxima, the script can be run as:
 *   batch("/path/to/specfun.mac")
 */


/*
 * The test cases are performed in two scripts because neither Maxima
 * nor Python (SciPy) fully support special functions.
 */


block(

  print("Gamma(3) = ", float(gamma(3)) ),
  print("Gamma(4.2) = ", gamma(4.2) ),
  print("Gamma(0.51) = ", gamma(0.51) ),
  print("Gamma(0.23) = ", gamma(0.23) ),
  print("Gamma(-1.7) = ", gamma(-1.7) ),
  print("Gamma(-4.56) = ", gamma(-4.56) ),
  print("Gamma(2-i) = ", float(gamma(2-%i)) ),
  print("Gamma(0.7+1.2i) = ", gamma(0.7+1.2*%i) ),
  print("Gamma(-2.3-2.1i) = ", gamma(-2.3-2.1*%i) ),

  print("Beta(4, 5) = ", float(beta(4,5)) ),
  print("Beta(3.2, 1-0.5i) = ", beta(3.2, 1-0.5*%i) ),
  print("Beta(-2+3.7i, 0.7-1.3i) = ", beta(-2+3.7*%i, 0.7-1.3*%i) ),

  print("Upper inc. Gamma(2, 0.5) = ", gamma_incomplete(2, 0.5) ),
  print("Upper inc. Gamma(2, 5) = ", gamma_incomplete(2, 5.0) ),
  print("Lower inc. Gamma(3, 2.5) = ", gamma(3) - gamma_incomplete(3, 2.5) ),
  print("Lower inc. Gamma(1.5, 4) = ", gamma(1.5) - gamma_incomplete(1.5, 4) ),
  print("Reg. upper inc. Gamma(3, 0.5) = ", gamma_incomplete_regularized(3, 0.5) ),
  print("Reg. lower inc. Gamma(1.5, 3.2) = ", 1 - gamma_incomplete_regularized(1.5, 3.2) ),
  print("Upper inc. Gamma(2+i, 1-i) = ", gamma_incomplete(2.0+%i, 1.0-%i) ),
  print("Lower inc. Gamma(1.4-0.7i, 0.3+0.1i) = ", gamma(1.4-0.7*%i) - gamma_incomplete(1.4-0.7*%i, 0.3+0.1*%i) ),
  print("Reg. upper inc. Gamma(-1.1+0.8i, 2.4-1.3i) = ", gamma_incomplete_regularized(-1.1+0.8*%i, 2.4-1.3*%i) ),
  print("Reg. lower inc. Gamma(-3.2-1.4i, -2-0.5i) = ", 1 - gamma_incomplete_regularized(-3.2-1.4*%i, -2-0.5*%i) ),

  print("Lower inc. Beta(2, 5, 0.2) = ", beta_incomplete(2, 5, 0.2) ),
  print("Lower inc. Beta(2, 5, 0.7) = ", beta_incomplete(2, 5, 0.7) ),
  print("Upper inc. Beta(1, 2, 0.15) = ", beta(1, 2) - beta_incomplete(1, 2, 0.15) ),
  print("Upper inc. Beta(1, 2, 0.82) = ", beta(1, 2) - beta_incomplete(1, 2, 0.82) ),
  print("Reg. lower inc. Beta(3, 2, 0.12) = ", beta_incomplete_regularized(3, 2, 0.12) ),
  print("Reg. upper inc. Beta(4, 1, 0.32) = ", 1 - beta_incomplete_regularized(4, 1, 0.32) ),
  print("Lower inc. Beta(2-i, 3+i, 0.1+0.1i) = ", beta_incomplete(2.0-%i, 3.0+%i, 0.1+0.1*%i) ),
  print("Upper inc. Beta(-1.2+i, -3-i, 0.1-0.2i) = ", beta(-1.2+%i, -3.0-%i) - beta_incomplete(-1.2+%i, -3.0-%i, 0.1-0.2*%i) ),
  print("Reg. lower inc. Beta((2.2-0.2i, 1.4+0.7i, -0.3+0.4i) = ", beta_incomplete_regularized(2.2-0.2*%i, 1.4+0.7*%i, -0.3+0.4*%i) ),
  print("Reg. upper inc. Beta(-3.8-0.7i, -3.4+2.7i, -0.6-0.1i) = ", 1 - beta_incomplete_regularized(-3.8-0.7*%i, -3.4+2.7*%i, -0.6-0.1*%i) )

  /* the rest of test cases are performed in 'specfun.py' */
)$
