/*
 * A Maxima script that reproduces the first part of expected results of the
 * test module 'test/specfunTest.cpp'.
 * The other part is performed in 'scripts/test/specfun.py'.
 *
 * From a shell, run the script as:
 *   maxima -b /path/to/specfun.mac
 *
 * From Maxima/wxMaxima, the script can be run as:
 *   batch("/path/to/specfun.mac")
 */

float(gamma(3));
gamma(4.2);
gamma(0.51);
gamma(0.23);
gamma(-1.7);
gamma(-4.56);
float(gamma(2-%i));
gamma(0.7+1.2*%i);
gamma(-2.3-2.1*%i);

float(beta(4,5));
beta(3.2, 1-0.5*%i);
beta(-2+3.7*%i, 0.7-1.3*%i);

gamma_incomplete(2, 0.5);
gamma_incomplete(2, 5.0);
gamma(3) - gamma_incomplete(3, 2.5);
gamma(1.5) - gamma_incomplete(1.5, 4);
gamma_incomplete_regularized(3, 0.5);
1 - gamma_incomplete_regularized(1.5, 3.2);
gamma_incomplete(2.0+%i, 1.0-%i);
gamma(1.4-0.7*%i) - gamma_incomplete(1.4-0.7*%i, 0.3+0.1*%i);
gamma_incomplete_regularized(-1.1+0.8*%i, 2.4-1.3*%i);
1 - gamma_incomplete_regularized(-3.2-1.4*%i, -2-0.5*%i);

beta_incomplete(2, 5, 0.2);
beta_incomplete(2, 5, 0.7);
beta(1, 2) - beta_incomplete(1, 2, 0.15);
beta(1, 2) - beta_incomplete(1, 2, 0.82);
beta_incomplete_regularized(3, 2, 0.12);
1 - beta_incomplete_regularized(4, 1, 0.32);
beta_incomplete(2.0-%i, 3.0+%i, 0.1+0.1*%i);
beta(-1.2+%i, -3.0-%i) - beta_incomplete(-1.2+%i, -3.0-%i, 0.1-0.2*%i);
beta_incomplete_regularized(2.2-0.2*%i, 1.4+0.7*%i, -0.3+0.4*%i);
1 - beta_incomplete_regularized(-3.8-0.7*%i, -3.4+2.7*%i, -0.6-0.1*%i);

/* the rest of test cases are performed in 'specfun.py' */
